Added check to ensure steghide is installed

diff --git a/stegcracker b/stegcracker
--- a/stegcracker
+++ b/stegcracker
@@ -9,8 +9,19 @@ if [ $# -eq 0 ]; then
     exit 1
 else
     wordlist=${2:-/usr/share/wordlists/rockyou.txt}
-    echo "Attacking file '$1' with wordlist '$wordlist'.."
 fi
+
+# Ensure steghide is installed
+if [[ ! $(which steghide) ]]; then
+    echo -e "\x1B[31mError:\x1B[0m Steghide does not appear to be installed, or has not been added to your current PATH."
+
+    if [[ $(cat /etc/issue | grep Kali && which apt-get) ]]; then
+        echo "       You can install it by running the following command: apt-get install steghide -y"
+    fi
+
+    exit 1
+fi
+
 
 # Ensure the input file exists
 if [ ! -f $1 ]; then
@@ -31,6 +42,8 @@ if [ -f $1.out ]; then
 fi
 
 # Crack the file and quit upon finding the right one
+echo "Attacking file '$1' with wordlist '$wordlist'.."
+
 while read pass; do
     if steghide extract -sf $1 -xf $1.out -p "$pass" -f > /dev/null 2>&1; then
         echo "Successfully cracked file with password: $pass"
